---
  - name: Ensure old versions of Docker are not installed
    package:
      name: "{{ item }}"
      state: absent
    with_items:
      - docker
      - docker-engine

  - name: Ensure dependencies are installed
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates

  - name: Docker apt key is added
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present

  - name: Ensure docker repository is enabled
    apt_repository:
      repo: "{{ docker_apt_repository }}"
      state: present
      update_cache: yes
